<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /** @var $block \Magento\Framework\Pricing\Render\Amount */ ?>
<style>
    .old-price span.price-tax-comment {
        display: none;
    }
    .catalog-product-view .product-info-main .product-info-price .price-box .price-final_price>span {
        display: initial !important;
    }
    .catalog-product-view .price-box.price-final_price {
        display: block !important;
        padding-bottom: 0 !important;
    }
    .catalog-product-view .product-info-main .product-info-stock-sku{
        display: block !important;
        padding-bottom: 10px !important;
    }
    /*.price-box.price-final_price :not(.special-price) {
        margin-bottom: 0 !important;
    }
    .price-box.price-final_price {
        margin-top: 21px !important;
    }
    .products-grid .special-price {
        width: 66%;
    }
    .products-grid .old-price {
        width: 15%;
        float: left;
    }*/
</style>
<span class="price-container <?= $block->escapeHtmlAttr($block->getAdjustmentCssClasses()) ?>"
        <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>
    <?php if ($block->getDisplayLabel()) : ?>
        <span class="price-label"><?= $block->escapeHtml($block->getDisplayLabel()) ?></span>
    <?php endif; ?>
    <span <?php if ($block->getPriceId()) : ?> id="<?= $block->escapeHtmlAttr($block->getPriceId()) ?>"<?php endif; ?>
        <?= ($block->getPriceDisplayLabel()) ? 'data-label="' . $block->escapeHtmlAttr($block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes()) . '"' : '' ?>
        data-price-amount="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>"
        data-price-type="<?= $block->escapeHtmlAttr($block->getPriceType()) ?>"
        class="price-wrapper <?= $block->escapeHtmlAttr($block->getPriceWrapperCss()) ?>"
    ><?= $block->escapeHtml($block->formatCurrency($block->getDisplayValue(), (bool)$block->getIncludeContainer()), ['span']) ?></span>
    <span style="color:red" class="price-tax-comment">. - incl. 20% MWSt</span>
    <?php if ($block->hasAdjustmentsHtml()) : ?>
        <?= $block->getAdjustmentsHtml() ?>
    <?php endif; ?>
    <?php if ($block->getSchema()) : ?>
        <meta itemprop="price" content="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>"/>
        <meta itemprop="priceCurrency" content="<?= $block->escapeHtmlAttr($block->getDisplayCurrencyCode()) ?>"/>
    <?php endif; ?>
</span>

